# Generated by Django 3.1.6 on 2021-02-19 08:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='attachmentName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
