# Generated by Django 3.1.6 on 2021-02-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210219_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
