# Generated by Django 3.1.6 on 2021-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210220_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='body'),
        ),
    ]
