# Generated by Django 3.1.4 on 2021-02-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('super_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('email', models.CharField(default='Email', max_length=255)),
                ('mobile', models.CharField(default='014555', max_length=255)),
                ('address', models.TextField(default='Address', max_length=350)),
                ('site_logo_url', models.CharField(default='Logo url', max_length=255)),
                ('site_logo_name', models.CharField(default='Logo name', max_length=255)),
                ('fb', models.CharField(default='Facebook Link', max_length=450)),
                ('tw', models.CharField(default='Facebook Link', max_length=450)),
                ('instagrm', models.CharField(default='Facebook Link', max_length=450)),
                ('pinterest', models.CharField(default='Facebook Link', max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_category', models.CharField(default='FAQ Category', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_category_id', models.IntegerField(default=0)),
                ('faq_category', models.CharField(default='FAQ', max_length=150)),
                ('faq_question', models.CharField(default='FAQs', max_length=255)),
                ('faq_ans', models.TextField(default='FAQs Ans', max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Front_end_slider_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img_name', models.CharField(default='Image Name', max_length=255)),
                ('slider_img_url', models.CharField(default='Image url', max_length=255)),
                ('slider_img_title', models.CharField(default='Image title', max_length=255)),
                ('slider_img_subtitle', models.CharField(default='Image subtitle', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter_Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_email', models.CharField(default='Email', max_length=255)),
                ('subscribing_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Category Name', max_length=35, unique=True)),
                ('category_id', models.IntegerField(default=0)),
                ('category_adding_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Username', max_length=150)),
                ('name', models.CharField(default='Name', max_length=150)),
                ('service_provider', models.BooleanField(default=False)),
                ('product_seller', models.BooleanField(default=False)),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='Service Name', max_length=150, unique=True)),
                ('service_id', models.IntegerField(default=0)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('adding_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(default='Name', max_length=60)),
                ('visitor_email', models.CharField(default='Email', max_length=255)),
                ('visitor_phone', models.CharField(default='Phone', max_length=20)),
                ('visitor_msg_subject', models.TextField(blank=True, default='Subject', null=True)),
                ('visitor_msg', models.TextField(default='Message')),
                ('visitor_msg_sending_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(default='Subcategory Name', max_length=150)),
                ('cat_id', models.IntegerField(default=0)),
                ('service_subcat_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('rel_with_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.service')),
            ],
        ),
        migrations.CreateModel(
            name='Product_subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(default='Subcat', max_length=15, unique=True)),
                ('cat_id', models.IntegerField(default=0)),
                ('rel_with_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.product_category')),
            ],
        ),
    ]
