# Generated by Django 3.1.4 on 2021-02-24 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InPersonService_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Category', max_length=20)),
                ('img', models.ImageField(upload_to='')),
                ('adding_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posted_jobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField()),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='')),
                ('service_type_id', models.CharField(max_length=50)),
                ('service_type_in_character', models.CharField(max_length=50)),
                ('service_cat_id', models.IntegerField()),
                ('service_category_in_character', models.CharField(max_length=50)),
                ('service_subcat_id', models.IntegerField()),
                ('service_subcategory_in_character', models.CharField(max_length=50)),
                ('project_budget', models.IntegerField()),
                ('project_delivery_time', models.IntegerField()),
                ('project_posted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(default='Service Title', max_length=60)),
                ('service_description', models.TextField(default='Service Description')),
                ('service_related_img1', models.ImageField(upload_to='')),
                ('service_category', models.IntegerField(default=0)),
                ('service_subcategory', models.IntegerField(default=0)),
                ('seller_country', models.CharField(default='USA', max_length=30)),
                ('sellerCountryFullName', models.CharField(default='USA', max_length=30)),
                ('sellerStateFullName', models.CharField(default='', max_length=30)),
                ('seller_state', models.CharField(default='', max_length=30)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InPersonServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(default='Service Title', max_length=60)),
                ('service_description', models.TextField(default='Service Description')),
                ('service_related_img1', models.ImageField(upload_to='')),
                ('service_category', models.IntegerField(default=0)),
                ('service_subcategory', models.IntegerField(default=0)),
                ('seller_country', models.CharField(default='USA', max_length=30)),
                ('sellerCountryFullName', models.CharField(default='USA', max_length=30)),
                ('sellerStateFullName', models.CharField(default='', max_length=30)),
                ('seller_state', models.CharField(default='', max_length=30)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InPersonService_subcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Subcategory', max_length=20)),
                ('img', models.ImageField(upload_to='')),
                ('rel_with_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.inpersonservice_cat')),
            ],
        ),
    ]
